import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, ArrowDownLeft, ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronDown, CircleHelp, Clock3, Compass, DoorOpen, FileText, LayoutDashboard, LoaderCircle, LogOut, MapPin, Menu, MessageCircle, MoreHorizontal, Search, Shield, Sparkles, Users, X } from 'lucide-react';

const API = import.meta.env.VITE_API_URL || '';
async function api(path, { token, ...options } = {}) {
  if (window.location.protocol === 'file:') throw new Error('This is the offline interface preview. Sign-in needs the running app and its database. Follow README.md to start the services, then open http://localhost:5173.');
  let response;
  try {
    response = await fetch(`${API}/api${path}`, { ...options, headers: { 'content-type': 'application/json', ...(token ? { authorization: `Bearer ${token}` } : {}), ...options?.headers } });
  } catch {
    throw new Error('PeopleClock could not reach its API. Start the Node server and confirm MongoDB is configured, then try again.');
  }
  const data = await response.json().catch(() => ({}));
  if (!response.ok) {
    const message = data.error || data.detail || (response.status >= 500
      ? 'The PeopleClock API is unavailable. Start the Node server and check its MongoDB connection.'
      : `The request could not be completed (HTTP ${response.status}).`);
    throw new Error(message);
  }
  return data;
}
function AssistantStatus({ token }) {
  const [health, setHealth] = useState(null);
  useEffect(() => {
    let active = true;
    api('/assistant/health', { token }).then(data => { if (active) setHealth(data); }).catch(err => { if (active) setHealth({ ready: false, message: err.message }); });
    return () => { active = false; };
  }, [token]);
  const ready = health?.ready === true;
  return <span className={`online-pill ${ready ? '' : 'offline'}`} title={health?.message || 'Checking Gemini configuration'}><i/>{health ? (ready ? 'Gemini ready' : 'Setup needed') : 'Checking…'}</span>;
}
const time = (date) => date ? new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(new Date(date)) : '—';
const dateLong = (date) => new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).format(date);
const dateShort = (date) => date ? new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date(date)) : '—';
const duration = (start, end) => { if (!start || !end) return 'In progress'; const mins = Math.max(0, Math.floor((new Date(end) - new Date(start)) / 60000)); return `${Math.floor(mins / 60)}h ${mins % 60}m`; };
const initials = (name = '') => name.split(/\s+/).filter(Boolean).slice(0, 2).map(x => x[0]).join('').toUpperCase();
const colors = ['lavender', 'mint', 'peach', 'blue', 'rose'];

function App() {
  const [session, setSession] = useState(() => { try { return JSON.parse(localStorage.getItem('peopleclock-session')); } catch { return null; } });
  const [page, setPage] = useState('overview');
  const [menuOpen, setMenuOpen] = useState(false);
  const [toast, setToast] = useState('');
  useEffect(() => { if (session) localStorage.setItem('peopleclock-session', JSON.stringify(session)); else localStorage.removeItem('peopleclock-session'); }, [session]);
  const notify = useCallback((message) => { setToast(message); window.setTimeout(() => setToast(''), 3500); }, []);
  if (!session) return <Auth onSuccess={setSession} />;
  const logout = () => { setSession(null); setPage('overview'); };
  return <div className="app-shell">
    <aside className={`sidebar ${menuOpen ? 'open' : ''}`}>
      <div className="brand"><span className="brand-mark"><Clock3 size={19} strokeWidth={2.4}/></span><span>people<span className="brand-light">clock</span></span></div>
      <div className="workspace-label">WORKSPACE</div><div className="workspace"><div className="workspace-symbol">N</div><div className="workspace-copy"><b>Northstar Studio</b><span>People operations</span></div><ChevronDown size={15} className="muted-icon"/></div>
      <div className="nav-label">MENU</div>
      <nav className="side-nav">
        <button className={page === 'overview' ? 'active' : ''} onClick={() => {setPage('overview');setMenuOpen(false)}}><LayoutDashboard size={18}/>Overview</button>
        {session.user.role === 'manager' && <button className={page === 'team' ? 'active' : ''} onClick={() => {setPage('team');setMenuOpen(false)}}><Users size={18}/>My team</button>}
        {session.user.role === 'employee' && <button className={page === 'attendance' ? 'active' : ''} onClick={() => {setPage('attendance');setMenuOpen(false)}}><CalendarDays size={18}/>My attendance</button>}
        <button className={page === 'assistant' ? 'active' : ''} onClick={() => {setPage('assistant');setMenuOpen(false)}}><MessageCircle size={18}/>Policy assistant<span className="new-dot"/></button>
      </nav>
      <div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><CircleHelp size={17}/></div><b>Need a hand?</b><p>Ask a question about company policies.</p><button onClick={() => setPage('assistant')}>Ask the assistant <ArrowRight size={14}/></button></div>
        <div className="profile-row"><Avatar name={session.user.name} tone="lavender"/><div className="profile-info"><b>{session.user.name}</b><span>{session.user.role === 'manager' ? 'Manager' : session.user.title}</span></div><button className="icon-button profile-menu" onClick={logout} aria-label="Sign out"><LogOut size={17}/></button></div>
      </div>
    </aside>
    {menuOpen && <button className="mobile-backdrop" aria-label="Close navigation" onClick={() => setMenuOpen(false)}/>}
    <main className="main-area"><header className="topbar"><button className="icon-button mobile-menu" onClick={() => setMenuOpen(v => !v)} aria-label="Open navigation"><Menu size={20}/></button><div className="breadcrumbs">Pages <span>/</span> <b>{page === 'team' ? 'My team' : page === 'attendance' ? 'My attendance' : page === 'assistant' ? 'Policy assistant' : 'Overview'}</b></div><div className="topbar-actions"><span className="secure-chip"><Shield size={14}/>Private workspace</span><span className="today-chip"><CalendarDays size={15}/>{new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(new Date())}</span><button className="top-avatar" title={session.user.name}>{initials(session.user.name)}</button></div></header>
      <div className="page-content">
        {session.user.role === 'manager' ? <ManagerPage key={page} page={page} session={session} notify={notify}/> : <EmployeePage key={page} page={page} session={session} notify={notify}/>}
      </div>
    </main>{toast && <div className="toast"><Check size={17}/>{toast}</div>}
  </div>;
}

function Avatar({ name, tone = 'lavender', size = '' }) { return <div className={`avatar ${tone} ${size}`}>{initials(name)}</div>; }

function Auth({ onSuccess }) {
  const [mode, setMode] = useState('login'); const [role, setRole] = useState('employee'); const [form, setForm] = useState({ name:'', email:'', password:'', confirmPassword:'', title:'', department:'', managerCode:'' }); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [visiblePasswords, setVisiblePasswords] = useState({}); const [busy, setBusy] = useState(false);
  const set = (key, value) => setForm(f => ({...f,[key]:value}));
  const passwordField = (label, key, placeholder, autoComplete, minLength = 8) => <label key={key}>{label}<span className="password-control"><input type={visiblePasswords[key]?'text':'password'} required minLength={minLength} value={form[key]} onChange={e=>set(key,e.target.value)} placeholder={placeholder} autoComplete={autoComplete}/><button type="button" className="password-visibility" aria-label={`${visiblePasswords[key]?'Hide':'Show'} ${label.toLowerCase()}`} onClick={()=>setVisiblePasswords(v=>({...v,[key]:!v[key]}))}>{visiblePasswords[key]?'Hide':'Show'}</button></span></label>;
  function switchMode(next) { setMode(next); setError(''); setNotice(''); setForm(f=>({...f,password:'',confirmPassword:''})); }
  async function submit(e) {
    e.preventDefault(); setBusy(true); setError(''); setNotice('');
    try {
      if (mode === 'forgot') { if (form.password !== form.confirmPassword) throw new Error('The passwords do not match.'); const result = await api('/auth/forgot-password', { method:'POST', body:JSON.stringify({ email:form.email, password:form.password, confirmPassword:form.confirmPassword }) }); setMode('login'); setForm(f=>({...f,password:'',confirmPassword:''})); setNotice(result.message); }
      else { const result = await api(`/auth/${mode === 'login' ? 'login' : 'register'}`, { method:'POST', body:JSON.stringify(mode === 'login' ? { email:form.email,password:form.password,role } : {...form,role}) }); onSuccess(result); }
    } catch (err) { setError(err.message); } finally { setBusy(false); }
  }
  const headings = { login:['Welcome back','Sign in to your workspace to pick up where you left off.'], register:['Create your account','Join your workspace and get your day started.'], forgot:['Choose a new password','Enter your registered work email and choose a new password.'] };
  return <div className="auth-screen"><div className="auth-decor"><div className="decor-orbit orbit-one"/><div className="decor-orbit orbit-two"/><div className="decor-card"><div className="decor-card-top"><span className="tiny-mark"><Clock3 size={14}/></span><span>Today's attendance</span><MoreHorizontal size={16}/></div><div className="decor-live"><span/><b>You're on the clock</b><small>09:02 AM</small></div><div className="decor-timeline"><span/><span/><span/><span/><span/><span/></div><div className="decor-card-foot"><span>MON, OCT 06</span><b>On time <Check size={13}/></b></div></div><div className="decor-note note-one"><div className="note-icon green"><MapPin size={15}/></div><span><b>Location captured</b><small>Only at clock-in & out</small></span></div><div className="decor-note note-two"><div className="note-icon purple"><Sparkles size={15}/></div><span><b>Policy answers</b><small>Grounded in your handbook</small></span></div><div className="auth-quote"><span className="quote-star">✳</span><p>Good work starts with<br/>a little <em>clarity.</em></p><small>A calmer way to work together.</small></div></div>
    <div className="auth-panel"><div className="auth-inner"><div className="brand auth-brand"><span className="brand-mark"><Clock3 size={19} strokeWidth={2.4}/></span><span>people<span className="brand-light">clock</span></span></div><div className="auth-welcome"><div className="eyebrow">PEOPLE OPERATIONS, SIMPLIFIED</div><h1>{headings[mode][0]}</h1><p>{headings[mode][1]}</p></div>
      {window.location.protocol === 'file:' && <div className="preview-notice"><CircleHelp size={16}/><span><b>Interface preview only</b><small>Sign-in and live data work when the app is run with its API and MongoDB. See README.md for setup.</small></span></div>}
      {(mode==='login'||mode==='register')&&<div className="role-select"><button className={role==='employee'?'selected':''} onClick={()=>setRole('employee')} type="button"><Users size={16}/>Employee</button><button className={role==='manager'?'selected':''} onClick={()=>setRole('manager')} type="button"><Shield size={16}/>Manager</button></div>}
      <form className="auth-form" onSubmit={submit}>{mode==='register'&&<><label>Full name<input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Your name" autoComplete="name"/></label><div className="field-pair"><label>Job title<input value={form.title} onChange={e=>set('title',e.target.value)} placeholder={role==='manager'?'People manager':'e.g. Product intern'}/></label><label>Department<input value={form.department} onChange={e=>set('department',e.target.value)} placeholder="e.g. Design"/></label></div></>}
        {(mode==='login'||mode==='register'||mode==='forgot')&&<label>Work email<input type="email" required value={form.email} onChange={e=>set('email',e.target.value)} placeholder="you@company.com" autoComplete="email"/></label>}
        {(mode==='login'||mode==='register')&&<>{passwordField('Password','password',mode==='register'?'At least 8 characters':'Enter your password',mode==='register'?'new-password':'current-password',mode==='register'?8:1)}{mode==='login'&&<button className="forgot-link" type="button" onClick={()=>switchMode('forgot')}>Forgot password?</button>}</>}
        {mode==='forgot'&&<>{passwordField('New password','password','At least 8 characters','new-password')}{passwordField('Confirm new password','confirmPassword','Enter it again','new-password')}</>}
        {mode==='register'&&role==='manager'&&<label>Manager registration code<input required value={form.managerCode} onChange={e=>set('managerCode',e.target.value)} placeholder="Ask your workspace admin"/></label>}
        {error&&<div className="form-error" role="alert">{error}</div>}{notice&&<div className="form-notice" role="status">{notice}</div>}<button disabled={busy} className="primary-button auth-submit">{busy?<><LoaderCircle size={17} className="spin"/>Please wait…</>:mode==='login'?'Sign in to workspace':mode==='register'?'Create account':'Update password'} {!busy&&<ArrowRight size={16}/>}</button></form>
      <div className="auth-switch">{mode==='login'?<>New to PeopleClock? <button onClick={()=>switchMode('register')}>Create an account</button></>:mode==='register'?<>Already have an account? <button onClick={()=>switchMode('login')}>Sign in</button></>:<>Remembered your password? <button onClick={()=>switchMode('login')}>Back to sign in</button></>}</div><div className="auth-footer"><span>Built for the way people work.</span><span>Privacy first <span className="footer-dot">·</span> Always</span></div>
    </div></div></div>;
}

function Heading({ eyebrow, title, description, action }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<div className="heading-action">{action}</div>}</div>; }
function StatCard({ label, value, change, icon: Icon, accent = 'mint', foot }) { return <div className="stat-card"><div className="stat-top"><span>{label}</span><span className={`stat-icon ${accent}`}><Icon size={18}/></span></div><div className="stat-value">{value}</div><div className="stat-foot">{change&&<span className="stat-change"><ArrowUpRight size={13}/>{change}</span>}{foot&&<span>{foot}</span>}</div></div>; }
function MapLink({ location }) { if (!location?.latitude) return <span className="location-missing"><MapPin size={14}/>Not shared</span>; const href = `https://www.openstreetmap.org/?mlat=${location.latitude}&mlon=${location.longitude}#map=16/${location.latitude}/${location.longitude}`; return <a className="location-link" href={href} target="_blank" rel="noreferrer"><MapPin size={14}/>{location.latitude.toFixed(3)}, {location.longitude.toFixed(3)}<ArrowUpRight size={12}/></a>; }
function requestClockLocation() {
  if (!navigator.geolocation) return Promise.resolve({ location: null, message: 'this browser does not support location. Try the latest version of Chrome' });
  const read = (options) => new Promise((resolve) => navigator.geolocation.getCurrentPosition(
    (position) => resolve({ location: { latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy } }),
    (error) => resolve({ location: null, error }),
    options
  ));
  return (async () => {
    let result = await read({ enableHighAccuracy: true, timeout: 15000, maximumAge: 0 });
    if (result.location || result.error?.code === 1) return { ...result, message: locationErrorMessage(result.error) };
    result = await read({ enableHighAccuracy: false, timeout: 15000, maximumAge: 0 });
    return { ...result, message: locationErrorMessage(result.error) };
  })();
}
function locationErrorMessage(error) {
  if (!error) return 'the browser did not return a location';
  if (error.code === 1) return 'location permission is blocked. In Chrome, open the site controls beside the address bar, set Location to Allow, and reload';
  if (error.code === 2) return 'your device could not determine a location. Turn on Windows Location services and check your internet or Wi-Fi connection';
  if (error.code === 3) return 'the location request timed out. Turn on device Location and try again near a window or outdoors';
  return 'the browser could not determine your location. Check site permissions and device Location settings';
}

function EmployeePage({ page, session, notify }) {
  const [records,setRecords]=useState([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [question,setQuestion]=useState(''); const [messages,setMessages]=useState([]); const [asking,setAsking]=useState(false);
  const load=useCallback(async()=>{try{const d=await api('/attendance/mine',{token:session.token});setRecords(d.records)}catch(e){notify(e.message)}finally{setLoading(false)}},[session.token,notify]);
  useEffect(()=>{load()},[load]);
  const current=records.find(r=>!r.clockOut); const completed=records.filter(r=>r.clockOut); const today=new Date().toDateString(); const todays=records.filter(r=>new Date(r.clockIn).toDateString()===today);
  async function clock(action){setBusy(true);try{const {location,message}=await requestClockLocation();await api(`/attendance/${action}`,{token:session.token,method:'POST',body:JSON.stringify({location})});await load();notify(location?'Attendance saved with location.':`Attendance saved, but ${message}.`)}catch(e){notify(e.message)}finally{setBusy(false)}}
  async function ask(e){e.preventDefault();if(!question.trim())return;const q=question.trim();setQuestion('');setMessages(m=>[...m,{role:'user',text:q}]);setAsking(true);try{const r=await api('/assistant/ask',{token:session.token,method:'POST',body:JSON.stringify({question:q})});setMessages(m=>[...m,{role:'assistant',text:r.answer,sources:r.sources||[]}])}catch(err){setMessages(m=>[...m,{role:'assistant',text:err.message,error:true}])}finally{setAsking(false)}}
  if(page==='assistant') return <><Heading eyebrow="HERE WHEN YOU NEED IT" title="Policy assistant" description="Ask a question. Answers come from your company handbook."/><div className="assistant-layout"><div className="assistant-main"><div className="assistant-header"><div className="assistant-icon"><Sparkles size={18}/></div><div><b>Your HR policy assistant</b><span>Grounded in company documents</span></div><AssistantStatus token={session.token}/></div><div className="chat-area">{!messages.length&&<div className="chat-welcome"><div className="chat-spark"><Sparkles size={22}/></div><h2>What would you like to know?</h2><p>I’ll look through the company handbook and point you to the relevant policy.</p><div className="suggestions"><button onClick={()=>setQuestion('How many leaves can an intern get?')}>How many leaves can an intern get? <ArrowRight size={14}/></button><button onClick={()=>setQuestion('How should I request planned time off?')}>How should I request time off? <ArrowRight size={14}/></button><button onClick={()=>setQuestion('Does the app track my location all day?')}>Does the app track my location all day? <ArrowRight size={14}/></button></div></div>}{messages.map((m,i)=><div key={i} className={`chat-message ${m.role} ${m.error?'chat-error':''}`}><div className="chat-avatar">{m.role==='assistant'?<Sparkles size={15}/>:initials(session.user.name)}</div><div className="chat-bubble">{m.text}{m.sources?.length>0&&<div className="sources"><FileText size={13}/>Sources: {m.sources.join(', ')}</div>}</div></div>)}{asking&&<div className="chat-message assistant"><div className="chat-avatar"><Sparkles size={15}/></div><div className="chat-bubble thinking"><span/><span/><span/></div></div>}</div><form className="chat-form" onSubmit={ask}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about leave, working hours, attendance…"/><button disabled={asking||!question.trim()} aria-label="Send question"><ArrowRight size={18}/></button></form><div className="chat-privacy">Answers are generated from company policy documents. For personal situations, check with your manager.</div></div><aside className="assistant-aside"><div className="aside-card"><div className="aside-illustration"><FileText size={23}/></div><h3>Grounded in your handbook</h3><p>The assistant retrieves relevant policy passages before answering. If a policy doesn’t cover your question, it’ll say so.</p></div><div className="aside-card mini"><div className="aside-card-icon"><Shield size={17}/></div><div><b>Your privacy matters</b><p>Your questions are only used to find the right policy for you.</p></div></div></aside></div></>;
  if(page==='attendance') return <><Heading eyebrow="YOUR WORK HISTORY" title="My attendance" description="Your clock events and the locations shared at those moments."/><div className="content-card"><div className="card-heading"><div><h3>Recent clock events</h3><p>Your latest attendance records</p></div><span className="record-count">{records.length} records</span></div><div className="table-wrap"><table><thead><tr><th>DATE</th><th>CLOCK IN</th><th>LOCATION</th><th>CLOCK OUT</th><th>HOURS</th><th>LOCATION</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td><b>{dateShort(r.clockIn)}</b><small>{new Intl.DateTimeFormat(undefined,{weekday:'short'}).format(new Date(r.clockIn))}</small></td><td>{time(r.clockIn)}</td><td><MapLink location={r.clockInLocation}/></td><td>{time(r.clockOut)}</td><td>{duration(r.clockIn,r.clockOut)}</td><td><MapLink location={r.clockOutLocation}/></td></tr>)}{!records.length&&!loading&&<tr><td colSpan="6" className="empty-cell">No attendance records yet. Clock in to start your first one.</td></tr>}</tbody></table>{loading&&<div className="loading-row"><LoaderCircle className="spin" size={18}/>Loading attendance…</div>}</div></div><div className="privacy-inline"><Shield size={15}/>Location is requested only when you clock in or out. <a href="https://www.openstreetmap.org" target="_blank" rel="noreferrer">View on OpenStreetMap <ArrowUpRight size={12}/></a></div></>;
  return <><Heading eyebrow="YOUR WORKSPACE" title={`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, ${session.user.name.split(' ')[0]}.`} description={dateLong(new Date())}/>
    <div className="employee-hero"><div className="hero-copy"><div className="hero-kicker"><span className="live-dot"/>{current?'YOUR SHIFT IS IN PROGRESS':'READY WHEN YOU ARE'}</div><h2>{current?`Clocked in at ${time(current.clockIn)}`:'A fresh day, on your time.'}</h2><p>{current?'Your time is being recorded. Remember to clock out when you wrap up.':'Clock in when you’re ready to get started. Your location is only requested for this event.'}</p>{current?<div className="shift-since"><Clock3 size={16}/><span>Started <b>{time(current.clockIn)}</b></span><span className="shift-divider">·</span><span>{dateShort(current.clockIn)}</span></div>:<div className="hero-meta"><span><MapPin size={14}/>One-time location request</span><span><Shield size={14}/>Private and secure</span></div>}</div><div className="clock-widget"><div className="clock-date">{new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric'}).format(new Date())}</div><div className="clock-time">{new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',hour12:true}).format(new Date())}</div><div className="clock-zone">LOCAL TIME</div><button disabled={busy} className={`clock-action ${current?'clock-out':''}`} onClick={()=>clock(current?'clock-out':'clock-in')}>{busy?<LoaderCircle className="spin" size={17}/>:current?<DoorOpen size={17}/>:<ArrowUpRight size={17}/>} {current?'Clock out':'Clock in'}</button></div><div className="hero-decoration decor-circle"/><div className="hero-decoration decor-line"/></div>
    <div className="stats-grid employee-stats"><StatCard label="Today's clock-ins" value={todays.length} foot="attendance events" icon={ArrowDownLeft} accent="mint"/><StatCard label="Completed shifts" value={completed.length} foot="all time" icon={Check} accent="lavender"/><StatCard label="Account type" value={session.user.role==='employee'?'Employee':'Manager'} foot={session.user.department||'General'} icon={Users} accent="peach"/></div>
    <div className="section-heading"><div><h2>Recent activity</h2><p>Your most recent clock events</p></div><button className="text-button" onClick={()=>window.dispatchEvent(new CustomEvent('navigate-attendance'))}>View all <ArrowRight size={15}/></button></div>
    <div className="content-card activity-card"><div className="activity-head"><div className="activity-heading"><span className="activity-symbol"><Activity size={16}/></span><div><b>Attendance history</b><span>Latest activity in your account</span></div></div><span className="record-count">{records.length} records</span></div>{loading?<div className="loading-row"><LoaderCircle className="spin" size={18}/>Loading your activity…</div>:records.slice(0,4).map(r=><div className="activity-row" key={r.id}><div className="activity-date"><b>{dateShort(r.clockIn)}</b><span>{new Intl.DateTimeFormat(undefined,{weekday:'short'}).format(new Date(r.clockIn))}</span></div><div className="activity-track"><span className="track-dot in"/><span className="track-line"/><span className={`track-dot ${r.clockOut?'out':'pending'}`}/></div><div className="activity-event"><span><ArrowDownLeft size={13}/>In <b>{time(r.clockIn)}</b></span><span><ArrowUpRight size={13}/>Out <b>{time(r.clockOut)}</b></span></div><div className="activity-duration">{duration(r.clockIn,r.clockOut)}</div><span className={`status-pill ${r.clockOut?'complete':'active'}`}>{r.clockOut?'Completed':'In progress'}</span></div>)}{!records.length&&!loading&&<div className="empty-state"><span className="empty-icon"><Clock3 size={21}/></span><b>No clock-ins yet</b><p>Your attendance activity will show up here.</p></div>}</div>
    <div className="privacy-inline"><Shield size={15}/>Location is only requested at the moment you clock in or out. <a onClick={()=>window.dispatchEvent(new CustomEvent('navigate-attendance'))}>See attendance history <ArrowRight size={12}/></a></div>
    <NavigationEvents/>
  </>;
}
function NavigationEvents(){useEffect(()=>{const handler=()=>{const nav=[...document.querySelectorAll('.side-nav button')].find(b=>b.textContent.includes('attendance'));nav?.click()};window.addEventListener('navigate-attendance',handler);return()=>window.removeEventListener('navigate-attendance',handler)},[]);return null}

function ManagerPage({ page, session, notify }) {
 const [data,setData]=useState({employees:[],records:[],active:[]});const [loading,setLoading]=useState(true);const [query,setQuery]=useState('');const [question,setQuestion]=useState('');const [messages,setMessages]=useState([]);const [asking,setAsking]=useState(false);
 const load=useCallback(async()=>{try{setData(await api('/manager/overview',{token:session.token}))}catch(e){notify(e.message)}finally{setLoading(false)}},[session.token,notify]);useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[load]);
 const employeeById=useMemo(()=>new Map(data.employees.map(e=>[e.id,e])),[data.employees]);
 const filtered=useMemo(()=>data.employees.filter(e=>`${e.name} ${e.email} ${e.department} ${e.title}`.toLowerCase().includes(query.toLowerCase())),[data.employees,query]);
 async function ask(e){e.preventDefault();if(!question.trim())return;const q=question.trim();setQuestion('');setMessages(m=>[...m,{role:'user',text:q}]);setAsking(true);try{const r=await api('/assistant/ask',{token:session.token,method:'POST',body:JSON.stringify({question:q})});setMessages(m=>[...m,{role:'assistant',text:r.answer,sources:r.sources||[]}])}catch(err){setMessages(m=>[...m,{role:'assistant',text:err.message,error:true}])}finally{setAsking(false)}}
 if(page==='assistant')return <><Heading eyebrow="HERE WHEN YOU NEED IT" title="Policy assistant" description="Ask a question about the company handbook."/><div className="assistant-layout"><div className="assistant-main"><div className="assistant-header"><div className="assistant-icon"><Sparkles size={18}/></div><div><b>Your HR policy assistant</b><span>Grounded in company documents</span></div><AssistantStatus token={session.token}/></div><div className="chat-area">{messages.length===0&&<div className="chat-welcome"><div className="chat-spark"><Sparkles size={22}/></div><h2>How can I help your team?</h2><p>Get a quick answer from company policy documents.</p><div className="suggestions"><button onClick={()=>setQuestion('How many leaves can an intern get?')}>How many leaves can an intern get? <ArrowRight size={14}/></button><button onClick={()=>setQuestion('What are the standard work hours?')}>What are the standard work hours? <ArrowRight size={14}/></button></div></div>}{messages.map((m,i)=><div key={i} className={`chat-message ${m.role} ${m.error?'chat-error':''}`}><div className="chat-avatar">{m.role==='assistant'?<Sparkles size={15}/>:initials(session.user.name)}</div><div className="chat-bubble">{m.text}{m.sources?.length>0&&<div className="sources"><FileText size={13}/>Sources: {m.sources.join(', ')}</div>}</div></div>)}{asking&&<div className="chat-message assistant"><div className="chat-avatar"><Sparkles size={15}/></div><div className="chat-bubble thinking"><span/><span/><span/></div></div>}</div><form className="chat-form" onSubmit={ask}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about leave or working hours…"/><button disabled={asking||!question.trim()}><ArrowRight size={18}/></button></form><div className="chat-privacy">Answers are based on the company policy documents. Check with HR for exceptions.</div></div><aside className="assistant-aside"><div className="aside-card"><div className="aside-illustration"><FileText size={23}/></div><h3>Grounded in your handbook</h3><p>Relevant policy passages are retrieved before answering. No answer is invented when there’s no policy match.</p></div><div className="aside-card mini"><div className="aside-card-icon"><Shield size={17}/></div><div><b>Private workspace</b><p>Only signed-in workspace members can use this assistant.</p></div></div></aside></div></>;
 if(page==='team')return <><Heading eyebrow="PEOPLE DIRECTORY" title="My team" description="People who have registered in your workspace." action={<span className="member-count"><Users size={15}/>{data.employees.length} members</span>}/><div className="content-card team-card"><div className="card-heading"><div><h3>Team members</h3><p>Employee accounts registered with the workspace</p></div><div className="search-box"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your team"/></div></div><div className="table-wrap"><table><thead><tr><th>TEAM MEMBER</th><th>DEPARTMENT</th><th>ROLE</th><th>STATUS</th></tr></thead><tbody>{filtered.map(e=>{const isActive=data.active.some(a=>a.employee?.id===e.id);return <tr key={e.id}><td><div className="person-cell"><Avatar name={e.name} tone={colors[e.name.length%colors.length]}/><div><b>{e.name}</b><small>{e.email}</small></div></div></td><td>{e.department||'General'}</td><td>{e.title||'Team member'}</td><td><span className={`status-pill ${isActive?'active':'neutral'}`}><i/>{isActive?'Working now':'Off the clock'}</span></td></tr>})}{filtered.length===0&&!loading&&<tr><td colSpan="4" className="empty-cell">{data.employees.length?'No team members match that search.':'Your team directory will fill as employees register.'}</td></tr>}</tbody></table>{loading&&<div className="loading-row"><LoaderCircle className="spin" size={18}/>Loading team…</div>}</div></div><div className="privacy-inline"><Users size={15}/>Team members appear here after registration. Share the employee sign-up page with your team.</div></>;
 return <><Heading eyebrow="PEOPLE OPERATIONS" title={`Hello, ${session.user.name.split(' ')[0]}.`} description={dateLong(new Date())} action={<span className="member-count live"><i/>{data.active.length} working now</span>}/><div className="manager-banner"><div className="banner-copy"><div className="hero-kicker"><span className="live-dot"/>LIVE TEAM OVERVIEW</div><h2>Your people, at a glance.</h2><p>Attendance updates automatically as your team clocks in and out.</p><div className="hero-meta"><span><MapPin size={14}/>Locations shared at clock events</span><span><Activity size={14}/>Refreshes every 30 seconds</span></div></div><div className="banner-graphic"><div className="graphic-ring ring-a"/><div className="graphic-ring ring-b"/><div className="graphic-center"><Users size={24}/></div><div className="graphic-count">{data.employees.length}<small>TEAM</small></div></div></div>
 <div className="stats-grid"><StatCard label="Team members" value={data.employees.length} foot="registered employees" icon={Users} accent="lavender"/><StatCard label="Working now" value={data.active.length} foot="currently clocked in" icon={Activity} accent="mint"/><StatCard label="Clock events" value={data.records.length} foot="latest 150 events" icon={Clock3} accent="peach"/></div>
 <div className="section-heading"><div><h2>Who's working</h2><p>Employees currently clocked in</p></div><button className="text-button" onClick={()=>window.dispatchEvent(new CustomEvent('navigate-team'))}>Team directory <ArrowRight size={15}/></button></div>
 <div className="content-card team-presence"><div className="presence-head"><div><h3>Live attendance</h3><p>Location captured at clock-in. No background tracking.</p></div><span className="live-label"><i/>LIVE</span></div>{data.active.length?data.active.map((r,i)=><div className="presence-row" key={r.id}><Avatar name={r.employee?.name||'Employee'} tone={colors[i%colors.length]}/><div className="presence-person"><b>{r.employee?.name||'Employee'}</b><span>{r.employee?.title||r.employee?.department||'Team member'} <span className="middot">·</span> In since {time(r.clockIn)}</span></div><div className="presence-location"><MapLink location={r.clockInLocation}/><span>Clock-in location</span></div><div className="presence-elapsed">{duration(r.clockIn,new Date())}</div></div>):<div className="empty-state"><span className="empty-icon"><Clock3 size={21}/></span><b>No one's clocked in yet</b><p>When an employee clocks in, their shift and shared location appear here.</p></div>}</div>
 <div className="section-heading compact"><div><h2>Recent clock events</h2><p>Latest attendance activity across the team</p></div><button className="refresh-button" onClick={load}><Activity size={15}/>Refresh</button></div>
 <div className="content-card"><div className="table-wrap"><table><thead><tr><th>EMPLOYEE</th><th>DATE</th><th>CLOCK IN</th><th>LOCATION AT IN</th><th>CLOCK OUT</th><th>LOCATION AT OUT</th><th>HOURS</th></tr></thead><tbody>{data.records.slice(0,8).map((r,i)=>{const e=r.employee||employeeById.get(r.employee);return <tr key={r.id}><td><div className="person-cell"><Avatar name={e?.name||'Employee'} tone={colors[i%colors.length]} size="small"/><div><b>{e?.name||'Employee'}</b><small>{e?.department||'General'}</small></div></div></td><td>{dateShort(r.clockIn)}</td><td>{time(r.clockIn)}</td><td><MapLink location={r.clockInLocation}/></td><td>{time(r.clockOut)}</td><td><MapLink location={r.clockOutLocation}/></td><td>{duration(r.clockIn,r.clockOut)}</td></tr>})}{data.records.length===0&&!loading&&<tr><td colSpan="7" className="empty-cell">No clock events yet. Attendance records will show here as employees use the app.</td></tr>}</tbody></table>{loading&&<div className="loading-row"><LoaderCircle className="spin" size={18}/>Loading attendance…</div>}</div></div>
 <div className="manager-footer"><Shield size={14}/>Location access is limited to coordinates voluntarily shared when an employee clocks in or out.</div><NavigationEvents/></>;
}

export default App;
